# Generated by Django 5.2.3 on 2025-06-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_timecapsule_sent_timecapsule_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecapsule',
            name='timezone',
        ),
    ]
