# Generated by Django 5.2.3 on 2025-06-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_timecapsule_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsule',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='capsule_uploads/'),
        ),
    ]
