# Generated by Django 5.2.3 on 2025-06-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_timecapsule_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsule',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
