# Generated by Django 5.2.3 on 2025-06-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_timecapsule_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsule',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
